# Copyright (c) Facebook, Inc. and its affiliates.
import math
import fvcore.nn.weight_init as weight_init
import torch
import torch.nn.functional as F
from torch import nn

from detectron2.layers import Conv2d, ShapeSpec, get_norm
# 注意nn.LayerNorm与detectron2 LN的不同之处

from .backbone import Backbone
from .build import BACKBONE_REGISTRY
from .dinov3 import build_dinov3_backbone

__all__ = [
    "build_dinov3_fpn_backbone",
    "FPN",
    "SimpleFeaturePyramid",
]


class FPN(Backbone):
    """
    This module implements :paper:`FPN`.
    It creates pyramid features built on top of some input feature maps.
    """

    _fuse_type: torch.jit.Final[str]

    def __init__(
        self,
        bottom_up,
        in_features,
        out_channels,
        norm="",
        top_block=None,
        fuse_type="sum",
        square_pad=0,
    ):
        """
        Args:
            bottom_up (Backbone): module representing the bottom up subnetwork.
                Must be a subclass of :class:`Backbone`. The multi-scale feature
                maps generated by the bottom up network, and listed in `in_features`,
                are used to generate FPN levels.
            in_features (list[str]): names of the input feature maps coming
                from the backbone to which FPN is attached. For example, if the
                backbone produces ["res2", "res3", "res4"], any *contiguous* sublist
                of these may be used; order must be from high to low resolution.
            out_channels (int): number of channels in the output feature maps.
            norm (str): the normalization to use.
            top_block (nn.Module or None): if provided, an extra operation will
                be performed on the output of the last (smallest resolution)
                FPN output, and the result will extend the result list. The top_block
                further downsamples the feature map. It must have an attribute
                "num_levels", meaning the number of extra FPN levels added by
                this block, and "in_feature", which is a string representing
                its input feature (e.g., p5).
            fuse_type (str): types for fusing the top down features and the lateral
                ones. It can be "sum" (default), which sums up element-wise; or "avg",
                which takes the element-wise mean of the two.
            square_pad (int): If > 0, require input images to be padded to specific square size.
        """
        super(FPN, self).__init__()
        assert isinstance(bottom_up, Backbone)
        assert in_features, in_features

        # Feature map strides and channels from the bottom up network (e.g. ResNet)
        input_shapes = bottom_up.output_shape()
        strides = [input_shapes[f].stride for f in in_features]
        in_channels_per_feature = [input_shapes[f].channels for f in in_features]

        _assert_strides_are_log2_contiguous(strides)
        lateral_convs = []
        output_convs = []

        use_bias = norm == ""
        for idx, in_channels in enumerate(in_channels_per_feature):
            lateral_norm = get_norm(norm, out_channels)
            output_norm = get_norm(norm, out_channels)

            lateral_conv = Conv2d(
                in_channels, out_channels, kernel_size=1, bias=use_bias, norm=lateral_norm
            )
            output_conv = Conv2d(
                out_channels,
                out_channels,
                kernel_size=3,
                stride=1,
                padding=1,
                bias=use_bias,
                norm=output_norm,
            )
            weight_init.c2_xavier_fill(lateral_conv)
            weight_init.c2_xavier_fill(output_conv)
            stage = int(math.log2(strides[idx]))
            self.add_module("fpn_lateral{}".format(stage), lateral_conv)
            self.add_module("fpn_output{}".format(stage), output_conv)

            lateral_convs.append(lateral_conv)
            output_convs.append(output_conv)
        # Place convs into top-down order (from low to high resolution)
        # to make the top-down computation in forward clearer.
        self.lateral_convs = lateral_convs[::-1]
        self.output_convs = output_convs[::-1]
        self.top_block = top_block
        self.in_features = tuple(in_features)
        self.bottom_up = bottom_up
        # Return feature names are "p<stage>", like ["p2", "p3", ..., "p6"]
        self._out_feature_strides = {"p{}".format(int(math.log2(s))): s for s in strides}
        # top block output feature maps.
        if self.top_block is not None:
            for s in range(stage, stage + self.top_block.num_levels):
                self._out_feature_strides["p{}".format(s + 1)] = 2 ** (s + 1)

        self._out_features = list(self._out_feature_strides.keys())
        self._out_feature_channels = {k: out_channels for k in self._out_features}
        self._size_divisibility = strides[-1]
        self._square_pad = square_pad
        assert fuse_type in {"avg", "sum"}
        self._fuse_type = fuse_type

    @property
    def size_divisibility(self):
        return self._size_divisibility

    @property
    def padding_constraints(self):
        return {"square_size": self._square_pad}

    def forward(self, x):
        """
        Args:
            input (dict[str->Tensor]): mapping feature map name (e.g., "res5") to
                feature map tensor for each feature level in high to low resolution order.

        Returns:
            dict[str->Tensor]:
                mapping from feature map name to FPN feature map tensor
                in high to low resolution order. Returned feature names follow the FPN
                paper convention: "p<stage>", where stage has stride = 2 ** stage e.g.,
                ["p2", "p3", ..., "p6"].
        """
        bottom_up_features = self.bottom_up(x)
        results = []
        prev_features = self.lateral_convs[0](bottom_up_features[self.in_features[-1]])
        results.append(self.output_convs[0](prev_features))

        # Reverse feature maps into top-down order (from low to high resolution)
        for idx, (lateral_conv, output_conv) in enumerate(
            zip(self.lateral_convs, self.output_convs)
        ):
            # Slicing of ModuleList is not supported https://github.com/pytorch/pytorch/issues/47336
            # Therefore we loop over all modules but skip the first one
            if idx > 0:
                features = self.in_features[-idx - 1]
                features = bottom_up_features[features]
                top_down_features = F.interpolate(prev_features, scale_factor=2.0, mode="nearest")
                lateral_features = lateral_conv(features)
                prev_features = lateral_features + top_down_features
                if self._fuse_type == "avg":
                    prev_features /= 2
                results.insert(0, output_conv(prev_features))

        if self.top_block is not None:
            if self.top_block.in_feature in bottom_up_features:
                top_block_in_feature = bottom_up_features[self.top_block.in_feature]
            else:
                top_block_in_feature = results[self._out_features.index(self.top_block.in_feature)]
            results.extend(self.top_block(top_block_in_feature))
        assert len(self._out_features) == len(results)
        return {f: res for f, res in zip(self._out_features, results)}

    def output_shape(self):
        return {
            name: ShapeSpec(
                channels=self._out_feature_channels[name], stride=self._out_feature_strides[name]
            )
            for name in self._out_features
        }


def _assert_strides_are_log2_contiguous(strides):
    """
    Assert that each stride is 2x times its preceding stride, i.e. "contiguous in log2".
    """
    for i, stride in enumerate(strides[1:], 1):
        assert stride == 2 * strides[i - 1], "Strides {} {} are not log2 contiguous".format(
            stride, strides[i - 1]
        )


class LastLevelMaxPool(nn.Module):
    """
    This module is used in the original FPN to generate a downsampled
    P6 feature from P5.
    """

    def __init__(self):
        super().__init__()
        self.num_levels = 1
        self.in_feature = "p5"

    def forward(self, x):
        return [F.max_pool2d(x, kernel_size=1, stride=2, padding=0)]


class LastLevelP6P7(nn.Module):
    """
    This module is used in RetinaNet to generate extra layers, P6 and P7 from
    C5 feature.
    """

    def __init__(self, in_channels, out_channels, in_feature="res5"):
        super().__init__()
        self.num_levels = 2
        self.in_feature = in_feature
        self.p6 = nn.Conv2d(in_channels, out_channels, 3, 2, 1)
        self.p7 = nn.Conv2d(out_channels, out_channels, 3, 2, 1)
        for module in [self.p6, self.p7]:
            weight_init.c2_xavier_fill(module)

    def forward(self, c5):
        p6 = self.p6(c5)
        p7 = self.p7(F.relu(p6))
        return [p6, p7]


# ------------------------------------------------------------------
# SimpleFeaturePyramid（来自 detectron2.modeling.backbone.vit）
#
# 复制原因：assert isinstance(net, Backbone)
# 可直接在此并列新增 class（如 MultilayerFPN），便于维护。
# ------------------------------------------------------------------
class SimpleFeaturePyramid(Backbone):
    """
    This module implements SimpleFeaturePyramid in :paper:`vitdet`.
    It creates pyramid features built on top of the input feature map.
    """

    def __init__(
        self,
        net,
        in_feature,
        out_channels,
        scale_factors,
        top_block=None,
        norm="LN",
        square_pad=0,
    ):
        """
        Args:
            net (Backbone): module representing the subnetwork backbone.
                Must be a subclass of :class:`Backbone`.
            in_feature (str): names of the input feature maps coming
                from the net.
            out_channels (int): number of channels in the output feature maps.
            scale_factors (list[float]): list of scaling factors to upsample or downsample
                the input features for creating pyramid features.
            top_block (nn.Module or None): if provided, an extra operation will
                be performed on the output of the last (smallest resolution)
                pyramid output, and the result will extend the result list. The top_block
                further downsamples the feature map. It must have an attribute
                "num_levels", meaning the number of extra pyramid levels added by
                this block, and "in_feature", which is a string representing
                its input feature (e.g., p5).
            norm (str): the normalization to use.
            square_pad (int): If > 0, require input images to be padded to specific square size.
        """
        super(SimpleFeaturePyramid, self).__init__()
        assert isinstance(net, Backbone)

        self.scale_factors = scale_factors

        input_shapes = net.output_shape()
        strides = [int(input_shapes[in_feature].stride / scale) for scale in scale_factors]
        _assert_strides_are_log2_contiguous(strides)

        dim = input_shapes[in_feature].channels
        self.stages = []
        use_bias = norm == ""
        for idx, scale in enumerate(scale_factors):
            out_dim = dim
            if scale == 4.0:
                layers = [
                    nn.ConvTranspose2d(dim, dim // 2, kernel_size=2, stride=2),
                    get_norm(norm, dim // 2),
                    nn.GELU(),
                    nn.ConvTranspose2d(dim // 2, dim // 4, kernel_size=2, stride=2),
                ]
                out_dim = dim // 4
            elif scale == 2.0:
                layers = [nn.ConvTranspose2d(dim, dim // 2, kernel_size=2, stride=2)]
                out_dim = dim // 2
            elif scale == 1.0:
                layers = []
            elif scale == 0.5:
                layers = [nn.MaxPool2d(kernel_size=2, stride=2)]
            else:
                raise NotImplementedError(f"scale_factor={scale} is not supported yet.")

            layers.extend(
                [
                    Conv2d(
                        out_dim,
                        out_channels,
                        kernel_size=1,
                        bias=use_bias,
                        norm=get_norm(norm, out_channels),
                    ),
                    Conv2d(
                        out_channels,
                        out_channels,
                        kernel_size=3,
                        padding=1,
                        bias=use_bias,
                        norm=get_norm(norm, out_channels),
                    ),
                ]
            )
            layers = nn.Sequential(*layers)

            stage = int(math.log2(strides[idx]))
            self.add_module(f"simfp_{stage}", layers)
            self.stages.append(layers)

        self.net = net
        self.in_feature = in_feature
        self.top_block = top_block
        # Return feature names are "p<stage>", like ["p2", "p3", ..., "p6"]
        self._out_feature_strides = {"p{}".format(int(math.log2(s))): s for s in strides}
        # top block output feature maps.
        if self.top_block is not None:
            for s in range(stage, stage + self.top_block.num_levels):
                self._out_feature_strides["p{}".format(s + 1)] = 2 ** (s + 1)

        self._out_features = list(self._out_feature_strides.keys())
        self._out_feature_channels = {k: out_channels for k in self._out_features}
        self._size_divisibility = strides[-1]
        self._square_pad = square_pad

    # 修正（相对 detectron2 原版）：原版 padding_constraints 的 key 拼成 "size_divisiblity"（少一个 i）
    # detectron2 的 ImageList.from_tensors 读的是正确拼写 "size_divisibility"
    # （image_list.py:96 `if "size_divisibility" in padding_constraints`），导致约束失效，
    # 输入图不会被 padding 到 16 的整数倍，DINOv3 ViT 断言失败。
    # detectron2 原版 ViTDet 默认用 square_pad 而非 size_divisibility，故此 bug 未暴露。
    @property
    def padding_constraints(self):
        return {
            "size_divisibility": self._size_divisibility,
            "square_size": self._square_pad,
        }

    def forward(self, x):
        """
        Args:
            x: Tensor of shape (N,C,H,W). H, W must be a multiple of ``self.size_divisibility``.

        Returns:
            dict[str->Tensor]:
                mapping from feature map name to pyramid feature map tensor
                in high to low resolution order. Returned feature names follow the FPN
                convention: "p<stage>", where stage has stride = 2 ** stage e.g.,
                ["p2", "p3", ..., "p6"].
        """
        bottom_up_features = self.net(x)
        features = bottom_up_features[self.in_feature]
        results = []

        for stage in self.stages:
            results.append(stage(features))

        if self.top_block is not None:
            if self.top_block.in_feature in bottom_up_features:
                top_block_in_feature = bottom_up_features[self.top_block.in_feature]
            else:
                top_block_in_feature = results[self._out_features.index(self.top_block.in_feature)]
            results.extend(self.top_block(top_block_in_feature))
        assert len(self._out_features) == len(results)
        return {f: res for f, res in zip(self._out_features, results)}


class MultilayerFPN(Backbone):
    """多层 ViT patch 特征 → 固定 4 尺度 P2/P3/P4/P5（无 top-down 融合，DEIMv2 STA 风格）

    注：
      - SimpleFPN 只取 backbone 的【单个】特征（最后一层），用 ConvTranspose2d 上采样出多尺度；
      - MultilayerFPN 取 backbone 的【多个】中间层特征，每层各自双线性插值/池化到目标 stride，
        层与层之间不融合（无 top-down 横向加法）。
        DEIMv2 的 Spatial Tuning Adapter 思路
        （为冻结 ViT 设计，比 SimpleFPN 更充分利用多层语义）

    尺度分配（固定 4 个，与 SimpleFPN 输出尺寸一致）：
        feats[0] → P2 (stride 4)  双线性插值放大 4 倍 (scale_factor=4.0)
        feats[1] → P3 (stride 8)  双线性插值放大 2 倍 (scale_factor=2.0)
        feats[2] → P4 (stride 16) 原特征图
        feats[3] → P5 (stride 32) MaxPool2d(kernel=2, stride=2) 缩小 2 倍

    复用规则（固定输出 4 尺度）：
        当 bottom_up 输出的特征数 < 4 时，缺失尺度复用最后一个特征。
        例如 OUT_INDICES=[8,10,12] → 去重后 3 个特征 → P2←f[0], P3←f[1], P4←f[2], P5←f[2]
              OUT_INDICES=[12]     → 1 个特征   → P2/P3/P4/P5 全用 f[0]

    每个 stage 结构：1x1 Conv2d(in_dim→out_channels) + norm + 3x3 Conv2d(out→out) + norm
        （与 SimpleFeaturePyramid stage 尾部的 layers.extend 一致）。
    """

    def __init__(
        self,
        net,
        out_feature_names,
        out_channels,
        norm="LN",
    ):
        """
        Args:
            net (Backbone): bottom_up（DINOv3Backbone）。
            out_feature_names (list[str]): bottom_up 的输出特征名，如 ["dinov3_stage0", ...]。
                浅层在前、深层在后。
            out_channels (int): 输出通道（须与 SparseRCNN.HIDDEN_DIM 一致，默认 256）。
            norm (str): stage 内 norm 类型（ViTDet 默认 "LN"）。
        """
        super().__init__()
        assert isinstance(net, Backbone)
        assert out_feature_names, "out_feature_names 不能为空"

        self.net = net
        self.in_features = tuple(out_feature_names)
        n_in = len(self.in_features)

        # 每个 ViT 层的通道数相同（embed_dim，ViT-B=768）
        input_shapes = net.output_shape()
        in_dim = input_shapes[self.in_features[0]].channels

        # 固定 4 个尺度，各建一组 stage
        self.stages = []
        use_bias = norm == ""
        for idx in range(4):
            layers = nn.Sequential(
                Conv2d(
                    in_dim,
                    out_channels,
                    kernel_size=1,
                    bias=use_bias,
                    norm=get_norm(norm, out_channels),
                ),
                Conv2d(
                    out_channels,
                    out_channels,
                    kernel_size=3,
                    padding=1,
                    bias=use_bias,
                    norm=get_norm(norm, out_channels),
                ),
            )
            weight_init.c2_xavier_fill(layers[0])
            weight_init.c2_xavier_fill(layers[1])
            self.add_module(f"mlfp_stage{idx}", layers)
            self.stages.append(layers)

        # P5 缩小
        self.downsample = nn.MaxPool2d(kernel_size=2, stride=2)  # MaxPool2d，与 SimpleFPN 一致
        # self.downsample = nn.AvgPool2d(kernel_size=2, stride=2)

        # 输出特征名 / stride / 通道
        self._out_features = ["p2", "p3", "p4", "p5"]
        self._out_feature_strides = {"p2": 4, "p3": 8, "p4": 16, "p5": 32}
        self._out_feature_channels = {k: out_channels for k in self._out_features}
        self._size_divisibility = input_shapes[self.in_features[0]].stride  # ViT patch_size=16

        # 记录输入特征数
        self.n_in_features = n_in

    @property
    def size_divisibility(self):
        return self._size_divisibility

    @property
    def padding_constraints(self):
        return {"size_divisibility": self._size_divisibility}

    def _idx_or_last(self, i):
        # 尺度 i 对应的特征 index，超出输入特征数时用最后一个
        return min(i, self.n_in_features - 1)

    def forward(self, x):
        """
        Args:
            x: 图像张量 (B, 3, H, W)，H/W 须为 patch_size 整数倍。

        Returns:
            dict[str->Tensor]: {"p2","p3","p4","p5"}，stride 4/8/16/32，通道 out_channels。
        """
        bottom_up_features = self.net(x)
        feats = [bottom_up_features[name] for name in self.in_features]

        # 固定 4 尺度，按 [P2,P3,P4,P5] 顺序，缺失复用最后一个
        f_p2 = feats[self._idx_or_last(0)]
        f_p3 = feats[self._idx_or_last(1)]
        f_p4 = feats[self._idx_or_last(2)]
        f_p5 = feats[self._idx_or_last(3)]

        results = [
            self.stages[0](F.interpolate(f_p2, scale_factor=4.0, mode="bilinear", align_corners=False)),
            self.stages[1](F.interpolate(f_p3, scale_factor=2.0, mode="bilinear", align_corners=False)),
            self.stages[2](f_p4),
            self.stages[3](self.downsample(f_p5)),
        ]
        return {name: res for name, res in zip(self._out_features, results)}

    def output_shape(self):
        return {
            name: ShapeSpec(
                channels=self._out_feature_channels[name], stride=self._out_feature_strides[name]
            )
            for name in self._out_features
        }


# ------------------------------------------------------------------
# DINOv3 backbone + Feature Pyramid
#
# 职责分层（H4/H5 重构后的清晰语义）：
#   - OUT_INDICES（cfg.MODEL.DINOv3.OUT_INDICES）：用于控制 DINOv3Backbone/wrapper 取哪些 transformer 层。
#     空 → 取最后一层；非空 → 取指定层。与 FPN 无关。
#   - FEATURE_STRATEGY（cfg.MODEL.DINOv3.FEATURE_STRATEGY）：用于构造 FPN。
#     与取层无关，但会校验 OUT_INDICES 产出的 bottom_up 是否满足该 FPN 的输入需求，不满足直接报错。
#
# 三种 FPN 构造策略：
#   - "simple"     （ViTDet 风格）：单输入 → SimpleFeaturePyramid 用 ConvTranspose2d 上/下采样出 P2-P5。
#                   要求 bottom_up 只输出 1 个 feature。
#   - "multilayer" （DEIMv2 STA 风格，无融合）：多输入 → MultilayerFPN 每层各自 双线性插值/MaxPool 到目标 stride，层间不融合。
#                   固定输出 4 尺度 P2-P5；特征数 < 4 时自动复用最后一个。
#                   允许 bottom_up 输出任意 ≥1 个 feature。
#   - "full_token" （阶段三预留）：保留 CLS/register，进阶注入检测头。目前与 simple 同路径。
# ------------------------------------------------------------------


@BACKBONE_REGISTRY.register()
def build_dinov3_fpn_backbone(cfg, input_shape: ShapeSpec):
    """构建 DINOv3 ViT + 特征金字塔。

    流程：先调用 build_dinov3_backbone 得到 bottom_up（DINOv3Backbone），
    再根据 FEATURE_STRATEGY 在其上构造 FPN，并校验 bottom_up 输出是否符合该 FPN 需求。

    字段：
        cfg.MODEL.DINOv3.WEIGHTS/OUT_INDICES/FREEZE  传给 build_dinov3_backbone（决定取层与冻结）
        cfg.MODEL.DINOv3.FEATURE_STRATEGY            决定 FPN 构造方式（见上方注释）
        cfg.MODEL.FPN.OUT_CHANNELS/NORM              FPN 参数

    Returns:
        backbone (Backbone): simple 策略下输出 P2..P5。
    """
    strategy = cfg.MODEL.DINOv3.FEATURE_STRATEGY
    out_channels = cfg.MODEL.FPN.OUT_CHANNELS

    # OUT_INDICES 由 build_dinov3_backbone 内部处理（空→最后一层，非空→指定层）。
    bottom_up = build_dinov3_backbone(cfg, input_shape)
    n_out = len(bottom_up._out_features)  # bottom_up 实际输出的 feature 数

    # 根据 FEATURE_STRATEGY 构造 FPN，并校验 bottom_up 输出
    if strategy == "simple" or strategy == "full_token":
        # SimpleFeaturePyramid：单输入 → 上/下采样出 P2/P3/P4/P5
        if n_out != 1:
            raise ValueError(
                f'FEATURE_STRATEGY="{strategy}" 要求 DINOv3Backbone 只输出 1 个 feature，'
                f"实际 {n_out} 个（{bottom_up._out_features}）。"
                f"请调整 OUT_INDICES 使其只取 1 层（如 OUT_INDICES: [] 取最后一层，或 [12]）。"
            )
        in_feature = bottom_up._out_features[0]   # "dinov3_stage0"
        backbone = SimpleFeaturePyramid(
            net=bottom_up,
            in_feature=in_feature,
            out_channels=out_channels,
            scale_factors=[4.0, 2.0, 1.0, 0.5],   # stride16 → P2(4)/P3(8)/P4(16)/P5(32)
            norm=cfg.MODEL.FPN.NORM,              # LN
            top_block=None,                       # scale_factors 已含 0.5 产出 P5，无需额外 top block
        )
        return backbone
    elif strategy == "multilayer":
        # MultilayerFPN：多输入（或单输入）→ 每层各自插值/池化到目标 stride，无融合。
        # 固定输出 4 尺度 P2/P3/P4/P5；特征数 < 4 时自动复用最后一个（见 MultilayerFPN docstring）。
        if n_out == 1:
            # 柔性提示：multilayer 但只取了 1 层，所有尺度将复用该层（仍可运行）。
            print(
                f'[MultilayerFPN] 提示：OUT_INDICES 只产出 {n_out} 个特征（{bottom_up._out_features}），'
                "4 个尺度将全部复用该层。若需多层，请在 OUT_INDICES 指定多层（如 [8, 10, 12, 12]）。"
            )
        in_features = bottom_up._out_features   # ["dinov3_stage0", ...]
        backbone = MultilayerFPN(
            net=bottom_up,
            out_feature_names=in_features,
            out_channels=out_channels,
            norm=cfg.MODEL.FPN.NORM,
        )
        return backbone
    else:
        raise ValueError(f"未知的 MODEL.DINOv3.FEATURE_STRATEGY: {strategy}")
